---
esphome:
  name: esp32-xiao-c3
  friendly_name: ESP32 XIAO C32
  on_boot:
    # - priority: 700
      then:
        - output.turn_on: my_slow_pwm
        - delay: 5s
        - output.set_level: 
            id: my_slow_pwm
            level: "50%"
        - script.execute: check_connections
        - script.wait: check_connections
    # - priority: 600
    #   then:
        - script.execute: initiate_sensors
        - script.wait: initiate_sensors
    # - priority: 500
    #   then:
        - script.execute: measure_water_level
        - script.wait: measure_water_level

        - script.execute: measure_soil_moisture
        - script.wait: measure_soil_moisture

        - script.execute: measure_temp_hum
        - script.wait: measure_temp_hum

        - if:
            condition:
              - lambda: |-
                 return id(soil_moisture_raw).state > id(wet_soil_value).state;
            then:
              - script.execute: pump_cycle
              - script.wait: pump_cycle
        
        - switch.turn_off: vcc_led
        - output.turn_off: my_slow_pwm
        - deep_sleep.enter: deep_sleep_1

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino

logger: 
  level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: true
  power_save_mode: light

  ap:
    ssid: "esp32-xiao-c3-fallback"
    password: "fallback123"

api:
  port: 6053

ota:
  - platform: esphome

mdns:
  disabled: false

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_pwd
  port: !secret mqtt_port
  topic_prefix: esp/xiao_c3

deep_sleep:
  id: deep_sleep_1
  sleep_duration: 3600s

############################# SCRIPTS #############################
script:
  - id: check_connections
    then:
### Check connections ###
      - wait_until:
          condition:
            wifi.connected:
          timeout: 10s
      # check wifi connection
      - if:
          condition:
            wifi.connected:
          then: 
            - logger.log: 
                level: INFO
                format: CONNECTED wifi 
      - if:
          condition:
            not: 
              wifi.connected:
          then: 
            - logger.log:
                level: WARN
                format: COULD NOT CONNECT wifi 
            - deep_sleep.enter: deep_sleep_1

      # check mqtt connection
      - wait_until:
          condition:
            mqtt.connected:
          timeout: 10s
      - if:
          condition:
            mqtt.connected:
          then: 
            - logger.log: 
                level: INFO
                format: CONNECTED mqtt 
      - if:
          condition:
            not: 
              mqtt.connected:
          then: 
            - logger.log:
                level: WARN
                format: COULD NOT CONNECT mqtt 
            - deep_sleep.enter: deep_sleep_1


  - id: initiate_sensors
    then:
      if: 
        all:  
          - wifi.connected:
          - mqtt.connected:
        then: 
        - switch.turn_on: vcc_waterlevel 
        - logger.log:
            level: INFO
            format: INITIATED Water Level Sensor 

        - switch.turn_on: vcc_soil_moisture 
        - logger.log:
            level: INFO
            format: INITIATED Soil Moisture Sensor 

        - switch.turn_on: vcc_temp_hum
        - logger.log:
            level: INFO
            format: INITIATED Temperature and Humidity Sensor   

        - delay: 10s 
  
        else:
          - logger.log:
              level: WARN
              format: Skipped initiation of sensors, because MQTT/WIFI NOT CONNECTED

  - id: measure_water_level
    then:
      - component.update: water_level_raw
      - delay: 5s
      - logger.log:
          level: INFO
          format: Water Level value updated
      - switch.turn_off: vcc_waterlevel
      # log water level
  
  - id: measure_soil_moisture
    then: 
      - component.update: soil_moisture_raw
      - delay: 5s
      - logger.log:
          level: INFO
          format: "Soil Moisture value updated: %.1f mV"
          args: ["id(soil_moisture_raw).state"]
      - switch.turn_off: vcc_soil_moisture

  - id: measure_temp_hum
    then:
      - component.update: temp_hum 
      - delay: 5s
      - logger.log:
          level: INFO
          format: "Temp./Hum. value updated: %.1f °C / %.1f %%" 
          args:
            - id(temperature).state
            - id(humidity).state
      - switch.turn_off: vcc_temp_hum
  # - id: calculate_moisture_value
  # lo calc
      # tbd
  
  - id: pump_cycle
    then: 
      - switch.turn_on: vcc_led
      - logger.log:
          level: INFO
          format: STARTING pump cycle
      - switch.turn_on: relay1
      - delay: !lambda return id(pump_duration).state * 1000;
      - switch.turn_off: relay1
      - logger.log: 
          level: INFO
          format: STOPPING pump cycle
      - switch.turn_off: vcc_led


output:
  platform: slow_pwm
  pin: GPIO9
  id: my_slow_pwm
  period: 500ms
############################# SCREEN #############################

# i2c:
#   sda: GPIO5
#   scl: GPIO6
#   scan: true

# font:
#   - file: "gfonts://Roboto"
#     id: font_small
#     size: 10

# display:
#   - platform: ssd1306_i2c
#     id: oled_display
#     model: "SSD1306 72x40"
#     address: 0x3C
#     contrast: 100%
#     lambda: |-
#       it.fill(COLOR_OFF);

#       it.printf(0, 0, id(font_small),
#                 "Humidity: %.0f %%", id(soil_percent).state);

#       it.printf(0, 16, id(font_small),
#                 "ADC: %.0f", id(soil_raw).state);


############################# SENSORS #############################

sensor:
  - name: "Soil Moisture"
    id: soil_moisture_raw
    pin: GPIO3
    platform: adc
    raw: true
    unit_of_measurement: "mV"
    attenuation: 12db
    update_interval: never

  - name: "Water Level"
    id: water_level_raw
    pin: GPIO4
    platform: adc
    raw: true
    unit_of_measurement: "mV"
    attenuation: 12db
    update_interval: never

  - id: temp_hum
    pin: GPIO6
    platform: dht
    model: dht11
    temperature:
      name: "Temperature"
      id: temperature
    humidity:
      name: "Humidity"
      id: humidity
    update_interval: never



#   - platform: template
#     id: soil_percent
#     name: ""
#     unit_of_measurement: "%"
#     lambda: |-
#       const float dry = 2500;   // trocken kalibrieren!
#       const float wet = 1460;   // nass kalibrieren!
#       float value = (dry - id(soil_raw).state) * 100.0 / (dry - wet);
#       if (value < 0) return 0;
#       if (value > 100) return 100;
#       return value;

############################# SWITCHES #############################

switch:
  # Relay
  - name: "Relay_1"
    id: relay1
    platform: gpio
    pin: 
      number: 5
      inverted: true
    restore_mode: ALWAYS_OFF

  - name: "Soil Moisture Power"
    id: vcc_soil_moisture
    platform: gpio
    pin: GPIO1
    
  - name: "Water Level Power"
    id: vcc_waterlevel
    platform: gpio
    pin: GPIO0

  - name: "Tem./Hum. Power"
    id: vcc_temp_hum
    platform: gpio
    pin: GPIO2

  - name: "Pump ON LED"
    id: vcc_led
    platform: gpio
    pin: GPIO10

############################# NUMBERS #############################

# Example configuration entry
number:
  - name: "Dry Soil Value"
    id: dry_soil_value
    platform: template
    optimistic: true
    min_value: 0
    max_value: 3650
    unit_of_measurement: "mV"
    step: 1
    restore_value: true

  - name: "Wet Soil Value"
    id: wet_soil_value
    platform: template
    optimistic: true
    min_value: 0
    max_value: 2000
    unit_of_measurement: "mV"
    step: 1
    restore_value: true

  - name: "Low Water Level Value"
    id: low_water_level_value
    platform: template
    optimistic: true
    min_value: 0
    max_value: 2000
    unit_of_measurement: "mV"
    step: 1
    restore_value: true

  - name: "High Water Level Value"
    id: high_water_level_value
    platform: template
    optimistic: true
    min_value: 0
    max_value: 2000
    unit_of_measurement: "mV"
    step: 1
    restore_value: true

  - name: "Pump Duration"
    id: pump_duration
    platform: template
    optimistic: true
    unit_of_measurement: "sec"
    min_value: 0
    max_value: 2000
    step: 1
    restore_value: true

  - name: "Deep Sleep Duration"
    id: deep_sleep_time
    platform: template
    optimistic: true
    min_value: 0
    max_value: 18000
    unit_of_measurement: "sec"
    step: 1
    restore_value: true



...
