---
esphome:
  name: esp32-xiao-c3
  friendly_name: ESP32 XIAO C3
  on_boot:
    - script.execute: measure_soil_moisture

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino

logger:
  level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: true
  power_save_mode: light

  ap:
    ssid: "esp32-xiao-c3-fallback"
    password: "fallback123"

api:
  port: 6053

ota:
  - platform: esphome

mdns:
  disabled: false

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_pwd
  port: !secret mqtt_port
  topic_prefix: esp/xiao_c3
  birth_message:
    topic: esp/xiao_c3
    payload: online
  will_message:
    topic: esp/xiao_c3
    payload: wtf

deep_sleep:
  id: deep_sleep_1
  sleep_duration: 3s

############################# SCRIPTS #############################
script:
  - id: measure_soil_moisture
    then:
      - switch.turn_on: vcc_soil_moisture
      - delay: 10s
      - if:
          condition:
            mqtt.connected:
          then: 
          - component.update: soil_moisture_raw
          - delay: 5s # delay to ensure data has time to be sent
          - logger.log: Soil Moisture raw value sent to database

          else:
          - logger.log: Failed sending to database
      - deep_sleep.enter: deep_sleep_1
#       - component.update: soil_percent
      - switch.turn_off: vcc_soil_moisture
  # - id: pump_water
  # - id: measure_water_level
  # - id: indicate_low_water_level
  # - id: indicate_pumping


############################# SCREEN #############################

# i2c:
#   sda: GPIO5
#   scl: GPIO6
#   scan: true

# font:
#   - file: "gfonts://Roboto"
#     id: font_small
#     size: 10

# display:
#   - platform: ssd1306_i2c
#     id: oled_display
#     model: "SSD1306 72x40"
#     address: 0x3C
#     contrast: 100%
#     lambda: |-
#       it.fill(COLOR_OFF);

#       it.printf(0, 0, id(font_small),
#                 "Humidity: %.0f %%", id(soil_percent).state);

#       it.printf(0, 16, id(font_small),
#                 "ADC: %.0f", id(soil_raw).state);


############################# SENSORS #############################

sensor:
  - name: "Soil Moisture Raw"
    id: soil_moisture_raw
    pin: GPIO3
    platform: adc
    raw: true
    attenuation: 12db
    update_interval: never


#   - platform: template
#     id: soil_percent
#     name: ""
#     unit_of_measurement: "%"
#     lambda: |-
#       const float dry = 2500;   // trocken kalibrieren!
#       const float wet = 1460;   // nass kalibrieren!
#       float value = (dry - id(soil_raw).state) * 100.0 / (dry - wet);
#       if (value < 0) return 0;
#       if (value > 100) return 100;
#       return value;

############################# SWITCHES #############################

switch:
  # Relay
  - name: "Relay_2"
    id: relay2
    platform: gpio
    pin: 
      number: 6
      inverted: true
    restore_mode: ALWAYS_OFF

  - name: "Soil Moisture Power"
    id: vcc_soil_moisture
    platform: gpio
    pin: GPIO0

############################# NUMBERS #############################

# Example configuration entry
number:
  - name: "Dry Soil Value"
    id: dry_soil_value
    platform: template
    optimistic: true
    min_value: 0
    max_value: 3650
    step: 1
    restore_value: true

  - name: "Wet Soil Value"
    id: wet_soil_value
    platform: template
    optimistic: true
    min_value: 0
    max_value: 2000
    step: 1
    restore_value: true

  - name: "Low Water Level Value"
    id: low_water_level_value
    platform: template
    optimistic: true
    min_value: 0
    max_value: 2000
    step: 1
    restore_value: true

  - name: "High Water Level Value"
    id: high_water_level_value
    platform: template
    optimistic: true
    min_value: 0
    max_value: 2000
    step: 1
    restore_value: true

  - name: "Pump Duration"
    id: pump_duration
    platform: template
    optimistic: true
    min_value: 0
    max_value: 2000
    step: 1
    restore_value: true




...
